# Generated by Django 2.2.9 on 2020-01-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
